# Graphite Mono Theme for aerofi
name   = "Graphite Mono"
author = "aerofi"

imports = [
    "colors/graphite-mono.toml",
    "layouts/graphite-split.toml",
]

[gui]
padding = 10.0

[presets.grid.element]
columns = 8
icon_size = 48.0
padding = [4.0, 4.0]
corner_radius = 8.0

[presets.list.element]
icon_size = 22.0
padding = [8.0, 12.0]
corner_radius = 8.0
